INSERT INTO userinfo (USER_ID, USER_PASSWD, USER_TYPE) VALUES ('admin', '123', '0');
INSERT INTO userinfo (USER_ID, USER_PASSWD, USER_TYPE) VALUES ('e.g.BSL14101', '123', '1');
INSERT INTO userinfo (USER_ID, USER_PASSWD, USER_TYPE) VALUES ('e.g.BTA14101', '123', '2');
